### ISSUE TITLE
XML backups get stuck

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/docker-wikibase#168]
**Describe the bug**
The XML backup script just gets stuck or takes forever to finish with no apparent output. Filtering for namespaces does not help.

For instance:
```
/usr/local/bin/php /var/www/html/maintenance/dumpBackup.php --current --output=gzip:/data/xml_backup_test.gz --filter=namespace:0 --conf /shared/LocalSettings.php
```
just hangs there, showing now output. Only after waiting several minutes it shows the process output for 1000 pages and an estimated finishing time > 1 month. Then it hangs again.

**Expected behavior**
(A clear and concise description of what you expected to happen.)

**To Reproduce**

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Additional context**
- In example, information about the device used for producing the bug

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] the main MaRDI project has been assigned as project

**Comment by eloiferrer** [comment]
If we don't need the XML backups I suggest we deactivate them permanently.
Regardless of that, we can create JSON backups of only the Wikibase entities.

**Comment by physikerwelt** [comment]
I would first try to exclude items and properties as well and test again.

**Comment by eloiferrer** [comment]
That is what I have done. Even trying with much more restrictive filters such as --filter=namespace:0 which should only include the main namespace, gets stuck.

**Comment by physikerwelt** [comment]
@eloiferrer did you see the following
> Only after waiting several minutes it shows the process output for 1000 pages 

for ns:0?

**Comment by eloiferrer** [comment]
Yes. For ns:0 and also with any other configuration I've tried. The script seems to get stuck from the very beginning, no matter the options.

**Comment by physikerwelt** [comment]
I would like to understand why this is the case. There should be less than 1000 pages in ns:0. So it should finish in one hour or less.

**Comment by physikerwelt** [comment]
I found my own docu on https://www.mediawiki.org/wiki/Manual:DumpBackup.php :-) and I think filter should go to the query but plugin would still process every page.

**Comment by physikerwelt** [comment]
@eloiferrer you are right. The namespace filter is not in the query. https://gerrit.wikimedia.org/r/c/mediawiki/core/+/504792 while I share the view of @brightbyte. Espcially with our memory limit for the single database setup, it will be impossible to run this daily. One option to get around would be to rewrite the query via the [hook.](https://m.mediawiki.org/wiki/Manual:Hooks/ModifyExportQuery) 
I think given the effort, we should exclude XML backups from the daily runs.

**Comment by eloiferrer** [comment]
XML backups have been deactivated in https://github.com/MaRDI4NFDI/docker-wikibase/pull/164
