### ISSUE TITLE
Extension versions and core version should match

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/docker-wikibase#2]
Some extensions use 
- [ ] 1_35 other use 1_37. Some are fetched from 

- [ ] Gerrit, others from GitHub

**Comment by aot29** [comment]
Es ist mir nicht möglich, dieses Issue zu transferieren und ich habe es nicht hingekriegt, das Issue im Projekt board aufzulisten.
@Hyper-Node kannst du bitte gucken, ob das geht?

![screenshot](https://user-images.githubusercontent.com/95299082/153847454-d4f4a240-f8df-464b-aa1c-c91e72eb9980.png)

**Comment by Hyper-Node** [comment]
Von wo nach wo transferrieren ?

**Comment by aot29** [comment]
nach portal-compose Issues meine ich

**Comment by Hyper-Node** [comment]
![grafik](https://user-images.githubusercontent.com/8139033/153855760-d0979aad-fb21-4c02-82fb-556280cc4d9b.png)

**Comment by aot29** [comment]
danke
