### ISSUE TITLE
Permissions: /var/www/html/images owned by root, should be www-data

### ISSUE THREAD

**Issue by dajuno** [MaRDI4NFDI/docker-wikibase#49]
The directory /var/www/html/images should belong to www-data:www-data, but is created for the root user (as everything else).

The Dockerfile should fix the permissions, else, to allow image upload, manual intervention is necessary (`chown www-data:www-data ...`)

**Comment by physikerwelt** [comment]
Yes, I don't understand the context however. Does this block the progress in the MaRDI project?

**Comment by dajuno** [comment]
It does. I wrote the missing tests for backup & restore of uploaded images (before, only sql and xml backups were tested), which which need to upload a test image. This fails due to wrong permissions being set.

**Comment by physikerwelt** [comment]
Ok I did review the pr
