### ISSUE TITLE
Logs are not shown with docker-compose logs

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/docker-wikibase#67]
**Describe the bug**
(A clear and concise description of what the bug is.)
There are no logs shown in portainer or when running docker-compose logs

**Expected behavior**
(A clear and concise description of what you expected to happen.)
there should be a log output for every page call

**To Reproduce**

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Additional context**
- In example, information about the device used for producing the bug

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] MaRDI_Project has been assigned as project

**Comment by physikerwelt** [comment]
the logs are written to /var/log on the container

**Comment by dajuno** [comment]
Probably due to #62 and #63. I'm on it.

**Comment by physikerwelt** [comment]
As far as I could see from the commits, it seems to me that the changes have been undone... I think it is only a minor problem if the logs are in /var/log I was just confused. So don't worry too much if you can't fix it

**Comment by dajuno** [comment]
Yes, the access.log was still a real file, but not explicitly tailed anymore. I manually set
`ln -sfT /dev/stderr "$APACHE_LOG_DIR/error.log"; 	ln -sfT /dev/stdout "$APACHE_LOG_DIR/access.log"; 	ln -sfT /dev/stdout "$APACHE_LOG_DIR/other_vhosts_access.log";` to revert this. After a restart of the container this seems to be working now.

**Comment by dajuno** [comment]
i.e., the code is fine, this was just due to the already existing files in the persistent volume /var/log/apache2
