### ISSUE TITLE
Reduce the number of different versions of extensions

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/docker-wikibase#80]
In our wikibase container, we use a large variety of versions for extensions _wmf_XX, REL_1_XX, master, and custom pinnings.

If no particular version of an extension is used we might want to consider using the version from

https://github.com/MWStake/nonwmf-extensions

otherwise, all the extensions create a sufficient maintenance overhead.

Thanks to @JeroenDeDauw for the link (in the WBSG meeting)

**Comment by eloiferrer** [comment]
@physikerwelt I am trying to at least put some order into this. Is there any reason for using the master branch of Math and MathSearch? Otherwise I would use the REL branch as we do for most of the other extensions.

**Comment by physikerwelt** [comment]
We are developing math and mathsearch ourselves and want to show the latest development in the portal. I think whenever, possible we should use the latest wmf branches as they are most stable.

**Comment by physikerwelt** [comment]
We have at least introduced variables for the versions, I think that is all we can do at this very moment.
