### ISSUE TITLE
Investigate problem with semantic drilldown

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/docker-wikibase#85]
In d07952e semantic drilldown was deactivated. Figure out what the problem is.

**Comment by eloiferrer** [comment]
This is the error:

Fatal error: Cannot redeclare smwfContLang() (previously declared in /var/www/html/extensions/SemanticMediaWiki/includes/GlobalFunctions.php:28) in /var/www/html/extensions/SemanticMediaWiki/includes/GlobalFunctions.php on line 28
