### ISSUE TITLE
Remove hack to install ExternalData with any composer version

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/docker-wikibase#94]
https://github.com/MaRDI4NFDI/docker-wikibase/blob/bf1e4baadd43606f0291717a57b8739edf7c62c6/Dockerfile#L158

We introduced that hack, but it should no longer be required as it was fixed by @YaronKoren, cf.

https://phabricator.wikimedia.org/T330485

@eloiferrer can you test that and coordinate with @LizzAlice so that it does not disturb her workflow?

**Comment by eloiferrer** [comment]
This has indeed been fixed, but it is still only on the master branch of ExternalData. 
I think it is better to wait until REL1_41 is published. Then we just need to delete the line and are not forced to use always the master branch of ExternalData. So I leave the issue open for now.

**Comment by physikerwelt** [comment]
Yes you can set yourself a reminder for the week after the scheduled release date of REL1_41
